name: Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  Formate:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format code
        run: swiftformat --lint --swiftversion 5.5 .
